[package]
name = "tokio-chat-common"
version = "0.1.0"
authors = ["John Gallagher <jgallagher@bignerdranch.com>"]

[dependencies]
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
tokio-core = "0.1"
byteorder = "1.0"
