[package]
name = "tokio-chat-server"
version = "0.1.0"
authors = ["John Gallagher <jgallagher@bignerdranch.com>"]

[dependencies]
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
futures = "0.1"
tokio-core = "0.1"
byteorder = "1.0"
tokio-chat-common = { path = "../tokio-chat-common" }
